version: '3.1'

services:
  db:
    image: postgres
    container_name: apivendas
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=apivendas
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
